spring:
  application:
    name: @project.artifactId@

logging:
  level:
    de.muenchen.xjustiz.xjustiz-document-converter: INFO

xjustiz:
  xsd:
    generated-package-base: # Must be configured
  interface:
    document:
      processor: # Must be configured
      json-adapter: # Must be configured