name: Build all

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Berlin # timezone
    steps:
      - uses: it-at-m/lhm_actions/action-templates/actions/action-checkout@691ffa2542ed7cc1c53c416d22ace9a153d5152f # v1.0.21
      - if: ${{ hashFiles(format('./{0}/package.json', matrix.app-path))!=null }}
        id: node
        uses: it-at-m/lhm_actions/action-templates/actions/action-npm-build@691ffa2542ed7cc1c53c416d22ace9a153d5152f # v1.0.21
        with:
          app-path: ""
      - if: ${{ hashFiles(format('./{0}/pom.xml', matrix.app-path))!=null }}
        id: maven
        uses: it-at-m/lhm_actions/action-templates/actions/action-maven-build@691ffa2542ed7cc1c53c416d22ace9a153d5152f # v1.0.21
        with:
          app-path: ""
